### ISSUE TITLE
bwrap: Failed to make / slave: Permission denied

### ISSUE THREAD

**Issue by tomtomjhj** [kaist-cp/infra-public#11]
opam에서 ocaml-system을 쓰려고 하는데 이런 에러가 나옵니다. (system ocaml이 설치되어있는 상태에서 `opam init`)
```
[ERROR] The compilation of ocaml-system failed at "/kaist-cp-home/jaehwang.jung/.opam/opam-init/hooks/sandbox.sh build ocaml gen_ocaml_config.ml".

#=== ERROR while compiling ocaml-system.4.08.1 ================================#
# context     2.0.5 | linux/x86_64 |  | https://opam.ocaml.org#5484ff3c
# path        ~/.opam/default/.opam-switch/build/ocaml-system.4.08.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build ocaml gen_ocaml_config.ml
# exit-code   1
# env-file    /tmp/opam-jaehwang.jung-39764/ocaml-system-39764-ad6566.env
# output-file /tmp/opam-jaehwang.jung-39764/ocaml-system-39764-ad6566.out
### output ###
# bwrap: Failed to make / slave: Permission denied
```

bwrap(bubblewrap)이 20.04에서 0.4로 올라오면서 생긴 문제가 아닐까 합니다. 19.10(0.3.3)까지는 잘 되던 기능입니다

Solution
```
rm -rf ~/.opam
opam init --disable-sandboxing
```

**Comment by jeehoonkang** [comment]
opam은 정말 이상하군요...  알려주셔서 감사합니다.

**Comment by jeehoonkang** [comment]
여전히 문제가 있나요?

**Comment by tomtomjhj** [comment]
지금은 재현이 안됩니다. 제가 opam을 로컬에서 2.1로 업그레이드해서 그런걸수도 있고 이미 opam init이 되어있어서 no-op이라 그런 걸 수도 있을 것 같네요.
일반적인 해결책은 컨테이너 실행할 때 namespace를 만들 수 있도록 previlged 옵션을 주는 것으로 알고 있습니다.

**Comment by jeehoonkang** [comment]
I can reproduce this bug while building https://cp-git.kaist.ac.kr/verification/smr ...

**Comment by Lee-Janggun** [comment]
Reproduced while building https://gitlab.mpi-sws.org/iris/lambda-rust/-/tree/masters/rusthornbelt on p11010.

**Comment by Lee-Janggun** [comment]
Reproduced while doing `opam init` after removing `.opam`.

**Comment by jeehoonkang** [comment]
coder에선 문제가 없는듯 합니다

**Comment by jeehoonkang** [comment]
`opam init --disable-sandboxing`
