### ISSUE TITLE
fuse: device not found, try 'modprobe fuse' first

### ISSUE THREAD

**Issue by tomtomjhj** [kaist-cp/infra-public#13]
sandbox에서 sshfs나 appimage등등을 쓰면 이런 메시지가 나옵니다
```
fuse: device not found, try 'modprobe fuse' first
$ modprobe fuse
modprobe: FATAL: Module fuse not found in directory /lib/modules/4.15.0-91-generic
```
이렇게 하면 되는 듯 하비낟.
https://github.com/s3fs-fuse/s3fs-fuse/issues/647#issuecomment-392697838

**Comment by jeehoonkang** [comment]
권한 추가해서 다시 sandbox 만들었습니다.  확인해보시겠어요?

**Comment by tomtomjhj** [comment]
`fuse: mount failed: Permission denied`
라고 하네요

**Comment by jeehoonkang** [comment]
다시 만들었습니다. 이걸 참고해서 security 설정을 더 relax했습니다: https://github.com/moby/moby/issues/16233#issuecomment-144924721

**Comment by tomtomjhj** [comment]
이제 잘 됩니다.
