### ISSUE TITLE
Boot takes 15 minutes

### ISSUE THREAD

**Issue by lomotos10** [kaist-cp/infra-public#34]
상황상 로그는 이렇게 첨부합니다...
![KakaoTalk_20200923_140153454](https://user-images.githubusercontent.com/48435475/93968840-7a35d180-fda5-11ea-8a5d-182ab4df40dd.jpg)

**Comment by jeehoonkang** [comment]
일단 lab server를 재부팅했습니다..  계속 문제가 존재하는지 알려주시면 감사하겠습니다.

**Comment by jeehoonkang** [comment]
해결된듯 합니다.
