### ISSUE TITLE
연구실 DNS 서버 불안정 문제

### ISSUE THREAD

**Issue by lkaybob** [kaist-cp/infra-public#36]
## 현상 설명

간헐적으로 사이트 접속을 할 때, 첫 로딩 시간이 매우 길거나, 실패하곤 합니다.

예를 들어, 어느 날에 처음으로 abc.com에 접속을 한다면 페이지 로딩까지 5초 이상 걸리며(체감상 기준, 최대 10초까지 걸리기도 함), 어떨 때는 "도메인 네임의 IP 주소를 찾을 수 없다"며 첫 접속이 튕기곤 합니다. 대신 첫 접속 이후(링크 이동, 혹은 새로고침)에는 이런 문제가 발생하지 않습니다.

## 예상 원인

첫 접속에서만 문제가 발생하는 것으로 보아, 도메인 네임 cache miss가 나는 것과 관련이 있지 않을까 싶습니다.

## 특이사항

체감상 특정 요일과 시간대에 따라 현상이 좀 심해지는 것 같은데, 이건 좀 더 지켜봐야할 것 같습니다.
(예. 월요일 오전에 심했다가 이후에는 이상 현상이 덜합니다. 실제로 월요일 저녁에 이상 현상을 재현을 해보려고 했는데, 재현이 잘 안 됐습니다.)

**Comment by jeehoonkang** [comment]
알려주셔서 감사합니다.  이런 문제의 특성상 디버깅은 매우 어려울 것으로 예상하는데...  혹시 문제가 지속되면 다시 답글로 알려주세요.

**Comment by lkaybob** [comment]
혹시 연구실 Desktop 설정에 Fallback DNS address를 추가할 수 있을까요?
(어제 정전으로 오늘 아침에 웹 사이트 접속을 할 수 없었던 점과 본 이슈를 어느정도 해결할 수 있을 것 같아 제안드려봅니다.)

**Comment by jeehoonkang** [comment]
앞으로 각자 깔기로 했습니다.
