### ISSUE TITLE
install-packages에 apt upgrade 필요

### ISSUE THREAD

**Issue by tomtomjhj** [kaist-cp/infra-public#37]
데스크탑용 install-packages에 `apt upgrade`를 넣어야만 nvidia driver 관련 패키지가 제대로 업데이트 되는 것 같습니다.

\+  데스크탑용 install-packages에 #31 이 아직 반영 안된 것 같습니다

**Comment by jeehoonkang** [comment]
- #31 반영했습니다.
- 재황님 데스크탑이 재설치를 안해서 install-packages가 옛날거인 것 같습니다.  재설치하면 해결되는 문제이므로 일단 close하겠습니다.
- 참고로 앞으로 kaist-cp-refresh.sh 스크립트를 사용하는 방향으로 유도하려 합니다...  install-packages는 약간 낡은 방식이라 maintain하기 하기 어려워서..

**Comment by tomtomjhj** [comment]
다른 분 데스크탑에서 생긴 문제입니다

2020년 10월 28일 (수) 오전 2:57, Jeehoon Kang <notifications@github.com>님이 작성:

**Comment by coolofficials** [comment]
제 workstation과 서윤님 workstation에서 발생했습니다. 메일 보내드린 해상도 이슈와 같은 이슈입니다.
