### ISSUE TITLE
mattermost를 zulip으로 교체

### ISSUE THREAD

**Issue by tomtomjhj** [kaist-cp/infra-public#41]
https://zulip.com/why-zulip/

> Zulip provides the benefits of real-time chat, while also being great at asynchronous communication. Zulip is inspired by email’s highly effective threading model: Every channel message has a topic, just like every message in email has a subject line.

(러스트 개발도 zulip으로 합니다 https://rust-lang.zulipchat.com)

**Comment by jeehoonkang** [comment]
- 홈페이지를 보니 말이 되는 어프로치인 것 같습니다.
- https://github.com/zulip/docker-zulip 을 시도해보겠습니다...
- 다만 리가시 데이타가 있어서 이걸 옮기는건 어떻게할지 고민이 좀 필요합니다.
