### ISSUE TITLE
kaist-cp-vivado 외: No route to host

### ISSUE THREAD

**Issue by lkaybob** [kaist-cp/infra-public#44]
-p 11001은 접속이 되는데, -p 13001과 -p 11005가 접속이 안 됩니다.

kaist-cp-vivado
```
ssh: connect to host cp-service.kaist.ac.kr port 13001: No route to host
```
kaist-cp-05 (아마도?)
```
ssh: connect to host cp-service.kaist.ac.kr port 11005: No route to host
```

**Comment by jeehoonkang** [comment]
- 불편을 드려 죄송합니다... 두 서버가 같은 머신에서 돌아가는데 (threadripper 3990x), 지금 확인해보니 그 머신이 죽었습니다.
- 서버용이 아닌 머신을 랙마운트해서 불안정한게 아닌가 추측되는데요, 일단 재부팅해보고 (5분내로 서비스들은 돌아올겁니다) 다시 문제가 발생하면 4층 랙으로 옮기기로 하겠습니다.

**Comment by jeehoonkang** [comment]
재부팅했습니다.  일단 닫겠습니다.  문제가 지속되면 근본적인 해결책을 모색하겠습니다.
