### ISSUE TITLE
kaist-cp-vivado: Vivado crashes with segfault

### ISSUE THREAD

**Issue by lkaybob** [kaist-cp/infra-public#45]
Vivado build container를 만들었지만 사용하고 있지 못하는 상황이라 이슈 스레드로 관리하는게 좋을 것 같아 등록합니다.

Xilinx 포럼에서 본 문제 관련하여 질문[1]을 올렸지만, OS 버전을 낮춰보라는 조언만 받고 답변이 끊긴 상태입니다.
그래서 일단 아래와 같이 진행하면 어떨까 합니다.

1. `kaist-cp-vivado` 컨테이너의 OS를 Ubuntu 18.04로 다운그레이드 시도
2. 1번 조치 후에도 Vivado crash 현상 발생시 bare-metal로 rollback (혹은 다른 대안 고려)
  * Ubuntu 20.04 bare-metal 환경에서는 이 문제가 안 나타나는 것으로 확인됩니다. 

(본 이슈는 Vivado를 crash 없이 사용할 수 있게 만들고 닫았으면 합니다.)

[1] https://forums.xilinx.com/t5/Synthesis/Undetermistic-crash-during-ip-creation/m-p/1187974

**Comment by jeehoonkang** [comment]
저는 그냥 지금 단계에서 baremetal로 rollback하는걸 제안합니다. 어떻게 보시나요?

**Comment by lkaybob** [comment]
Baremetal로 돌아가는게 확실하긴 해서... 교수님 괜찮으시다면 전 좋습니다.
혹시 서버 옮기실 계획이 없으시다면 바로 Rollback 진행해주셔도 됩니다.

**Comment by jeehoonkang** [comment]
감사합니다. 지금 꺼도 될까요? 끈 후에 성혁님이 (친구들과?) 4층 랙으로 옮겨주시면 감사드리겠습니다.

**Comment by lkaybob** [comment]
네 끄셔도 됩니다. 그럼 저 연구실에 (물리적으로) 금방 출근 후 옮기도록 하겠습니다.

**Comment by jeehoonkang** [comment]
껐어요

**Comment by lkaybob** [comment]
Baremetal로 변경 후 Vivado 재설치해서 빌드 시도해본 결과, container 안에서 겪었던 문제는 안 나타나서 이슈 닫겠습니다.
