### ISSUE TITLE
mm에 github private repo 연동이 안됨

### ISSUE THREAD

**Issue by tomtomjhj** [kaist-cp/infra-public#47]

**Comment by jeehoonkang** [comment]
- 아마 도메인에서 직접 serve되지 않고 `cp-service.kaist.ac.kr/mm` 처럼 directory에서 serve되서 그런게 아닌가 의심하고 있습니다.
- `cp-chat.kaist.ac.kr` 를 새로 신청하여 여기서 serve해보려 합니다.

**Comment by jeehoonkang** [comment]
subscription은 되는데 실제로 notification은 안오는 문제를 겪고 있습니다...

**Comment by jeehoonkang** [comment]
we moved to zulip
